/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IHealthPolicy } from "./IHealthPolicy";
export type { SampleProtocol } from "./SampleProtocol";
