/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface SampleProtocolInterface extends Interface {
  getFunction(
    nameOrSignature: "checkHealth" | "healthPolicy"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "HealthChecked"): EventFragment;

  encodeFunctionData(
    functionFragment: "checkHealth",
    values: [BytesLike, BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "healthPolicy",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "checkHealth",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "healthPolicy",
    data: BytesLike
  ): Result;
}

export namespace HealthCheckedEvent {
  export type InputTuple = [user: AddressLike, healthy: boolean];
  export type OutputTuple = [user: string, healthy: boolean];
  export interface OutputObject {
    user: string;
    healthy: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SampleProtocol extends BaseContract {
  connect(runner?: ContractRunner | null): SampleProtocol;
  waitForDeployment(): Promise<this>;

  interface: SampleProtocolInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  checkHealth: TypedContractMethod<
    [proof: BytesLike, publicInputs: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  healthPolicy: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "checkHealth"
  ): TypedContractMethod<
    [proof: BytesLike, publicInputs: BigNumberish[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "healthPolicy"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "HealthChecked"
  ): TypedContractEvent<
    HealthCheckedEvent.InputTuple,
    HealthCheckedEvent.OutputTuple,
    HealthCheckedEvent.OutputObject
  >;

  filters: {
    "HealthChecked(address,bool)": TypedContractEvent<
      HealthCheckedEvent.InputTuple,
      HealthCheckedEvent.OutputTuple,
      HealthCheckedEvent.OutputObject
    >;
    HealthChecked: TypedContractEvent<
      HealthCheckedEvent.InputTuple,
      HealthCheckedEvent.OutputTuple,
      HealthCheckedEvent.OutputObject
    >;
  };
}
