/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IHealthPolicy,
  IHealthPolicyInterface,
} from "../../SampleProtocol.sol/IHealthPolicy";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "proof",
        type: "bytes",
      },
      {
        internalType: "uint256[]",
        name: "publicInputs",
        type: "uint256[]",
      },
    ],
    name: "isHealthy",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IHealthPolicy__factory {
  static readonly abi = _abi;
  static createInterface(): IHealthPolicyInterface {
    return new Interface(_abi) as IHealthPolicyInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IHealthPolicy {
    return new Contract(address, _abi, runner) as unknown as IHealthPolicy;
  }
}
