/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IHealthPolicy__factory } from "./IHealthPolicy__factory";
export { SampleProtocol__factory } from "./SampleProtocol__factory";
