/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type {
  Signer,
  AddressLike,
  ContractDeployTransaction,
  ContractRunner,
} from "ethers";
import type { NonPayableOverrides } from "../../common";
import type {
  HealthPolicy,
  HealthPolicyInterface,
} from "../../HealthPolicy.sol/HealthPolicy";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_verifier",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "InvalidProof",
    type: "error",
  },
  {
    inputs: [],
    name: "VerificationFailed",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "proof",
        type: "bytes",
      },
      {
        internalType: "uint256[]",
        name: "publicInputs",
        type: "uint256[]",
      },
    ],
    name: "isHealthy",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "verifier",
    outputs: [
      {
        internalType: "contract IVerifier",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x60a0346100be57601f61035138819003918201601f19168301916001600160401b038311848410176100c3578084926020946040528339810103126100be57516001600160a01b038116908190036100be5780156100795760805260405161027790816100da8239608051818181610131015261020e0152f35b60405162461bcd60e51b815260206004820152601860248201527f496e76616c6964207665726966696572206164647265737300000000000000006044820152606490fd5b600080fd5b634e487b7160e01b600052604160045260246000fdfe608060408181526004908136101561001657600080fd5b600092833560e01c9081632b7ac3f3146101fa5750634e8ee36e1461003a57600080fd5b346101bb5760603660031901126101bb576001600160a01b038235818116036101f657602480359067ffffffffffffffff908183116101f257366023840112156101f25782860135938285116101ee57368286860101116101ee576044358381116101ea57366023820112156101ea5780880135918483116101e6578260051b368582850101116101e2578851631e8e1e1360e01b8152808b018a90526044810189905297601f978190870160648b01378b6064828b01015287199788910116880193606089860301868a015280606486015260018060fb1b03106101e257608488826020968296948984960185830137010301917f0000000000000000000000000000000000000000000000000000000000000000165afa9586156101d857879661016d575b60208787519015158152f35b909192939495506020933d85116101d0575b601f8501168501928311858410176101bf57505060209183918552810103126101bb575180151581036101bb5760209250903880808080610161565b8280fd5b634e487b7160e01b87526041905285fd5b3d945061017f565b85513d89823e3d90fd5b8a80fd5b8980fd5b8880fd5b8780fd5b8680fd5b8380fd5b84903461023d578160031936011261023d577f00000000000000000000000000000000000000000000000000000000000000006001600160a01b03168152602090f35b5080fdfea26469706673582212206e8fcd95c37237e421ee0acfbc097c13e2ef12ae0253abef1c35d8f0f56341b264736f6c63430008140033";

type HealthPolicyConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: HealthPolicyConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class HealthPolicy__factory extends ContractFactory {
  constructor(...args: HealthPolicyConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    _verifier: AddressLike,
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(_verifier, overrides || {});
  }
  override deploy(
    _verifier: AddressLike,
    overrides?: NonPayableOverrides & { from?: string }
  ) {
    return super.deploy(_verifier, overrides || {}) as Promise<
      HealthPolicy & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): HealthPolicy__factory {
    return super.connect(runner) as HealthPolicy__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): HealthPolicyInterface {
    return new Interface(_abi) as HealthPolicyInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): HealthPolicy {
    return new Contract(address, _abi, runner) as unknown as HealthPolicy;
  }
}
